### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by rlefevre** [carpe/elm-data#1]
Hi,

There is currently [a bug](https://github.com/elm/compiler/issues/1982) in elm that accepts packages documentation with `@docs` not starting at the beginning of a line but renders it incorrectly on https://package.elm-lang.org. 

This is what happens with your package: 
https://github.com/carpe/elm-data/blob/90456b6a3454e75aa9d103be07d98df822d4c312/src/ElmData/AuthConfig.elm#L6
renders incorrectly to:
https://package.elm-lang.org/packages/carpe/elm-data/1.0.0/ElmData-AuthConfig

You can put your `@docs` at the beginning of the line to fix it. 

Also note that putting indentation before text inside a comment means "code block" in markdown, so your comments are actually rendered as a code block (leading to strange syntax highlighing and no line wrapping). You most likely want instead:
```
{-| 
Configuration for how Authentication will be handled in your app.

@docs AuthConfig, default
-}
```

Lastly, you can preview your documentation for example with [elm-doc-preview](https://www.npmjs.com/package/elm-doc-preview) to check it before publishing:

```sh
$ npm install -g elm-doc-preview
```
Then in your package directory:
```sh
$ elm-doc-preview
# or just
$ edp
```

**Comment by SwiftEngineer** [comment]
Thanks for this! I fixed a few of the modules, the next couple should be fixed the next time I release.
